# Generated by Django 4.2 on 2026-03-02 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('items', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, null=True)),
                ('cancel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['owner_email', '-created_at'], name='api_backgro_owner_e_9e84ec_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['state', '-updated_at'], name='api_backgro_state_f5ad58_idx'),
        ),
    ]
