# Generated by Django 4.2 on 2026-02-26 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('gmail_app_password', models.CharField(blank=True, default='', max_length=255)),
                ('whatsapp_phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('whatsapp_access_token', models.TextField(blank=True, default='')),
                ('whatsapp_phone_number_id', models.CharField(blank=True, default='', max_length=64)),
                ('whatsapp_business_id', models.CharField(blank=True, default='', max_length=64)),
                ('whatsapp_templates', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Settings',
                'verbose_name_plural': 'Account Settings',
            },
        ),
    ]
