"""Constantes globais da aplicação."""

# Limites de taxa
DEFAULT_RATE_LIMIT_PER_MINUTE = 60
DEFAULT_RATE_LIMIT_PER_HOUR = 1000
DEFAULT_RATE_LIMIT_PER_DAY = 10000

# Email
EMAIL_MAX_RECIPIENTS_PER_REQUEST = 500
EMAIL_BATCH_SIZE = 50

# WhatsApp
WHATSAPP_MAX_MESSAGE_LENGTH = 4096
WHATSAPP_BATCH_DELAY_SECONDS = 0.1

# Paginação
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Status de email
EMAIL_STATUS_QUEUED = 'queued'
EMAIL_STATUS_SENDING = 'sending'
EMAIL_STATUS_SENT = 'sent'
EMAIL_STATUS_FAILED = 'failed'
EMAIL_STATUS_SKIPPED = 'skipped'

EMAIL_STATUS_CHOICES = [
    (EMAIL_STATUS_QUEUED, 'Enfileirado'),
    (EMAIL_STATUS_SENDING, 'Enviando'),
    (EMAIL_STATUS_SENT, 'Enviado'),
    (EMAIL_STATUS_FAILED, 'Falhou'),
    (EMAIL_STATUS_SKIPPED, 'Pulado'),
]
