# Generated by Django 5.2.5 on 2026-03-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Webhook Event',
                'verbose_name_plural': 'WhatsApp Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_index', models.PositiveIntegerField()),
                ('entry_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='notifications.whatsappwebhookevent')),
            ],
            options={
                'verbose_name': 'WhatsApp Webhook Entry',
                'verbose_name_plural': 'WhatsApp Webhook Entries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_index', models.PositiveIntegerField()),
                ('field', models.CharField(blank=True, max_length=80)),
                ('messaging_product', models.CharField(blank=True, max_length=40)),
                ('display_phone_number', models.CharField(blank=True, max_length=40)),
                ('phone_number_id', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='notifications.whatsappwebhookentry')),
            ],
            options={
                'verbose_name': 'WhatsApp Webhook Change',
                'verbose_name_plural': 'WhatsApp Webhook Changes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_index', models.PositiveIntegerField()),
                ('wa_id', models.CharField(db_index=True, max_length=40)),
                ('profile_name', models.CharField(blank=True, max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='notifications.whatsappwebhookchange')),
            ],
            options={
                'verbose_name': 'WhatsApp Webhook Contact',
                'verbose_name_plural': 'WhatsApp Webhook Contacts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_index', models.PositiveIntegerField()),
                ('whatsapp_message_id', models.CharField(db_index=True, max_length=255)),
                ('from_wa_id', models.CharField(db_index=True, max_length=40)),
                ('message_type', models.CharField(max_length=40)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('text_body', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.whatsappwebhookchange')),
            ],
            options={
                'verbose_name': 'WhatsApp Webhook Message',
                'verbose_name_plural': 'WhatsApp Webhook Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
