# Generated by Django 4.2 on 2026-03-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_whatsappoutboundmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(db_index=True, max_length=255)),
                ('media_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('media_type', models.CharField(default='image', max_length=40)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('sha256', models.CharField(blank=True, max_length=128)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='whatsapp/media/%Y/%m/%d/')),
                ('status', models.CharField(db_index=True, default='pending', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_asset', to='notifications.whatsappwebhookmessage')),
            ],
            options={
                'verbose_name': 'WhatsApp Media Asset',
                'verbose_name_plural': 'WhatsApp Media Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
