# Generated by Django 4.2 on 2026-04-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_rename_whatsappsender_business_id_to_waba_id'),
        ('notifications', '0003_whatsappmediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppPendingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(db_index=True, max_length=40)),
                ('button_payload', models.CharField(db_index=True, max_length=255)),
                ('media_type', models.CharField(default='document', max_length=40)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('caption', models.TextField(blank=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=128)),
                ('file', models.FileField(upload_to='whatsapp/pending/%Y/%m/%d/')),
                ('status', models.CharField(db_index=True, default='pending', max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('trigger_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_attachments', to='auth_app.whatsappsender')),
            ],
            options={
                'verbose_name': 'WhatsApp Pending Attachment',
                'verbose_name_plural': 'WhatsApp Pending Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsapppendingattachment',
            index=models.Index(fields=['sender', 'wa_id', 'button_payload', 'status'], name='notificatio_sender__72149a_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapppendingattachment',
            index=models.Index(fields=['sender', 'status', '-created_at'], name='notificatio_sender__d7f5ef_idx'),
        ),
    ]
